### PR TITLE
ObjectCollection implementation

### LINKED ISSUE #5: Specify how to implement collections of collections of tracks
eg. user containing playlists containing tracks or artist containing albums containing tracks

---
_This issue has been automatically created by [todo-actions](https://github.com/apps/todo-actions) based on a TODO comment found in [music_service_async_interface/__init__.py:15](https://github.com/FUMR/music-service-async-interface/blob/master/music_service_async_interface/__init__.py#L15). It will automatically be closed when the TODO comment is removed from the default branch (master)._

### PR DESCRIPTION
**Pull request by JuniorJPDJ**
It looks like it works pretty good :D 

```python
from music_service_async_interface import Object, TrackCollection, TrackCollectionSet

class Album(TrackCollection):
    from_id = from_url = get_id = get_url = lambda *a, **b: None

class Playlist(TrackCollection):
    from_id = from_url = get_id = get_url = lambda *a, **b: None

class Whatever:
    pass

TrackCollectionSet[Whatever]
Traceback (most recent call last):
    raise TypeError(f"collection_type need to be subclass of TrackCollection, got {collection_type} instead")
TypeError: collection_type need to be subclass of TrackCollection, got <class '__main__.Whatever'> instead

TrackCollectionSet[Album]
Out: music_service_async_interface.TrackCollectionSet[Album]

TrackCollectionSet[Album] == TrackCollectionSet[Album]
Out: True

TrackCollectionSet[Album] == TrackCollectionSet[Playlist]
Out: False

class Artist(TrackCollectionSet[Album]):
    from_id = from_url = get_id = get_url = lambda *a, **b: None

Artist()
Traceback (most recent call last):
    Artist()
TypeError: Can't instantiate abstract class Artist with abstract methods albums

class Artist(TrackCollectionSet[Album]):
    from_id = from_url = get_id = get_url = albums = lambda *a, **b: None

Artist()
Out: <__main__.Artist at 0x7f79030e8ee0>

class Artist(TrackCollectionSet[Playlist]):
    from_id = from_url = get_id = get_url = albums = lambda *a, **b: None

Artist()
Traceback (most recent call last):
    Artist()
TypeError: Can't instantiate abstract class Artist with abstract methods playlists

class Artist(TrackCollectionSet[Album], TrackCollectionSet[Playlist]):
    from_id = from_url = get_id = get_url = lambda *a, **b: None

Artist()
Traceback (most recent call last):
    Artist()
TypeError: Can't instantiate abstract class Artist with abstract methods albums, playlists


```

### CODE REVIEW

**Comment by JuniorJPDJ** [comment]
TODO: https://www.grammarly.com/blog/plural-nouns/

**Comment by JuniorJPDJ** [comment]
Wait a sec.. What if we just had one `ObjectCollection` instead of `TrackCollection` and `TrackCollectionSet`..
We could possibly create every collection with this class as:
```python
class Album(ObjectCollection[Track]):
  def tracks(self):
    ...

class Artist(ObjectCollection[Album]):
  def albums(self):
    ...
```

**Comment by loboda4450** [comment]
yea, it seems to be cleaner

edit: I mean ``ObjectCollection``

**Comment by divadsn** [comment]
I would suggest `MediaCollection`, since I suppose we use it for things streaming related, right?

**Comment by JuniorJPDJ** [comment]
@divadsn There is already the most basic object of `music-service` and it's called `Object`.
That would need change if we wanted to call collection `MediaCollection`

**Comment by divadsn** [comment]
> There is already the most basic object of music-service and it's called Object

I would suggest maybe in that case changing this `Object` name to some other name, as it shadows a built-in name.

While the name itself isn't directly shadowing the lower-case `object` name, it may be confusing for new people.

**Comment by JuniorJPDJ** [comment]
It doesn't shadow anything and need to be imported directly.
ATM it is being used in tidal-async like:
```python
import music_service_async_interface as generic

class Track(generic.Object):
    ...
```
This name is created in case it will be subclassed on something non-media-related but still music-service-related.
If you have better name which is not related to media itself - I'm waiting for your idea :D

**Comment by JuniorJPDJ** [comment]
Oh.. And `MediaCollection` is not a good name bcs we could eg. do
- `ObjectCollection[User]` when music service has groups of users implemented
- `ObjectCollection[Channel]` when you want to eg. list your subscriptions somewhere (eg. YouTube)

also IMO `Medium` is not good generic name for `User` nor `Channel`

**Comment by JuniorJPDJ** [comment]
```python
from music_service_async_interface import Track, ObjectCollection

class Album(ObjectCollection[Track]):
    pass

class Playlist(ObjectCollection[Track]):
    pass

class Artist(ObjectCollection[Album], ObjectCollection[Playlist]):
    from_id = from_url = get_id = get_url = lambda *a, **b: None

    async def albums(self):
        for i in range(5):
            yield f"Album {i}"

    async def playlists(self):
        for i in range(5):
            yield f"Playlist {i}"

a = Artist()

async for i in a.iter(Album):
    print(i)

Album 0
Album 1
Album 2
Album 3
Album 4

async for i in a.albums():
    print(i)

Album 0
Album 1
Album 2
Album 3
Album 4

async for i in a.iter(Playlist):
    print(i)

Playlist 0
Playlist 1
Playlist 2
Playlist 3
Playlist 4

async for i in a.playlists():
    print(i)

Playlist 0
Playlist 1
Playlist 2
Playlist 3
Playlist 4

async for i in a.iter(Track):
    print(i)

KeyError: <class 'music_service_async_interface.Track'>

```

**Review by wvffle — APPROVED** [review]

**Pull request merged**
